[package]
name = "json_parser"
version = "1.0.0"
edition = "2021"
description = ""
authors = ["Bahriantsev Ivan"]

[dependencies]
pest = "2.7.5"
pest_derive = "2.7.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.3"
